export { default as HomeLayout } from "./HomeLayout";
export { default as Landing } from "./Landing";
export { default as SingleCardProduct } from "./SingleCardProduct";
export { default as Products } from "./Products";
export { default as Cart } from "./Cart";
export { default as Error } from "./Error";
export { default as About } from "./About";
export { default as Orders } from "./Orders";
export { default as Checkout } from "./Checkout";
